import type { Ticket } from '../types/tickets';
import type { User } from '../types/Users';

export const dummyTickets: Ticket[] = [
  {
    id: 'TCK-001',
    type: 'bug',
    priority: 'high',
    assignedTo: 'u1',
    createdAt: new Date('2026-02-01T09:00:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-15T18:00:00'),
    activeUsers: ['u1', 'u2', 'u3'],
    todoAttached: [
      {
        todo: 'Fix auth bug',
        addedBy: 'u1',
        isDone: false,
        priority: 'high',
        dueDate: new Date('2026-02-10'),
        reporter: 'u3',
      },
      {
        todo: 'Write unit tests',
        addedBy: 'u2',
        isDone: false,
        priority: 'mid',
        dueDate: new Date('2026-02-12'),
        reporter: 'u1',
      },
    ],
    data: {
      title: 'Authentication Fails on Refresh',
      content: 'JWT token gets cleared on page reload.',
      description: 'Users are logged out unexpectedly after refreshing the dashboard page.',
      labels: ['bug', 'auth', 'urgent'],
      docs: [
        { title: 'auth-flow.md', uploadedDate: new Date('2026-02-01') },
        { title: 'jwt-spec.pdf', uploadedDate: new Date('2026-02-01') },
      ],
      messages: [
        {
          userSender: 'u1',
          text: 'I am looking into this issue.',
          time: new Date('2026-02-01T10:00:00'),
          docs: [],
        },
        {
          userSender: 'u3',
          userReply: ['u1'],
          text: 'Root cause found. localStorage gets wiped during hydration.',
          time: new Date('2026-02-02T09:30:00'),
          docs: [],
        },
        {
          userSender: 'u2',
          userReply: ['u3'],
          text: 'Should we move token handling to httpOnly cookies?',
          time: new Date('2026-02-02T11:00:00'),
          docs: [],
        },
      ],
    },
  },
  {
    id: 'TCK-002',
    type: 'feature',
    priority: 'mid',
    assignedTo: 'u5',
    createdAt: new Date('2026-02-03T11:30:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-20T17:00:00'),
    activeUsers: ['u1', 'u2'],
    todoAttached: [
      {
        todo: 'Design wireframe',
        addedBy: 'u5',
        isDone: false,
        priority: 'mid',
        dueDate: new Date('2026-02-12'),
        reporter: 'u2',
      },
      {
        todo: 'Get stakeholder approval',
        addedBy: 'u2',
        isDone: false,
        priority: 'mid',
        dueDate: new Date('2026-02-18'),
        reporter: 'u5',
      },
    ],
    data: {
      title: 'Redesign Ticket Dashboard',
      content: 'Improve UX and layout clarity.',
      description:
        'Current dashboard feels cluttered. Improve hierarchy and add filtering options.',
      labels: ['ui', 'enhancement'],
      docs: [],
      messages: [],
    },
  },
  {
    id: 'TCK-003',
    type: 'task',
    priority: 'low',
    assignedTo: 'u3',
    createdAt: new Date('2026-01-28T14:15:00'),
    status: 'done',
    dueAt: new Date('2026-02-05T12:00:00'),
    activeUsers: ['u1'],
    todoAttached: [
      {
        todo: 'Optimize query',
        addedBy: 'u3',
        isDone: true,
        priority: 'low',
        dueDate: new Date('2026-02-02'),
        reporter: 'u1',
      },
      {
        todo: 'Benchmark response time',
        addedBy: 'u3',
        isDone: true,
        priority: 'low',
        dueDate: new Date('2026-02-04'),
        reporter: 'u1',
      },
    ],
    data: {
      title: 'Database Query Optimization',
      content: 'Slow response when loading ticket list.',
      description: 'Optimize SQL joins and add indexing on priority and status columns.',
      labels: ['backend', 'performance'],
      docs: [],
      messages: [],
    },
  },
  {
    id: 'TCK-004',
    type: 'bug',
    priority: 'high',
    assignedTo: 'u10',
    createdAt: new Date('2026-02-05T08:45:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-10T16:00:00'),
    activeUsers: ['u1', 'u5', 'u100', 'u54', 'u1030', 'u51', 'u10'],
    todoAttached: [
      {
        todo: 'Validate inputs',
        addedBy: 'u10',
        isDone: false,
        priority: 'high',
        dueDate: new Date('2026-02-08'),
        reporter: 'u1',
      },
      {
        todo: 'Handle edge cases',
        addedBy: 'u100',
        isDone: false,
        priority: 'mid',
        dueDate: new Date('2026-02-09'),
        reporter: 'u10',
      },
    ],
    data: {
      title: 'Form Validation Error',
      content: 'Submission fails without visible error.',
      description: 'Users are submitting empty forms. Validation needs to block and show feedback.',
      labels: ['frontend', 'validation', 'bug'],
      docs: [],
      messages: [],
    },
  },
  {
    id: 'TCK-005',
    type: 'bug',
    priority: 'mid',
    assignedTo: 'u200',
    createdAt: new Date('2026-02-06T09:15:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-18T17:00:00'),
    activeUsers: ['u200', 'u1', 'u203'],
    todoAttached: [
      {
        todo: 'Implement pagination',
        addedBy: 'u200',
        isDone: false,
        priority: 'mid',
        dueDate: new Date('2026-02-12'),
        reporter: 'u1',
      },
      {
        todo: 'Add loading skeleton',
        addedBy: 'u203',
        isDone: false,
        priority: 'low',
        dueDate: new Date('2026-02-14'),
        reporter: 'u200',
      },
    ],
    data: {
      title: 'Pagination Not Working on Ticket List',
      content: 'Next page button does nothing.',
      description: 'When clicking next page, the UI does not update. API call seems correct.',
      labels: ['frontend', 'bug'],
      docs: [],
      messages: [],
    },
  },
  {
    id: 'TCK-006',
    type: 'bug',
    priority: 'high',
    assignedTo: 'u205',
    createdAt: new Date('2026-02-07T08:00:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-12T18:00:00'),
    activeUsers: ['u205', 'u202', 'u203'],
    todoAttached: [
      {
        todo: 'Audit logs',
        addedBy: 'u205',
        isDone: false,
        priority: 'high',
        dueDate: new Date('2026-02-09'),
        reporter: 'u203',
      },
      {
        todo: 'Check access control',
        addedBy: 'u202',
        isDone: false,
        priority: 'high',
        dueDate: new Date('2026-02-10'),
        reporter: 'u205',
      },
    ],
    data: {
      title: 'Unauthorized Access to Admin Panel',
      content: 'Non-admin user accessed admin route.',
      description: 'Role-based route protection failed under certain conditions.',
      labels: ['security', 'critical'],
      docs: [],
      messages: [],
    },
  },
  {
    id: 'TCK-007',
    type: 'feature',
    priority: 'low',
    assignedTo: 'u201',
    createdAt: new Date('2026-02-08T14:30:00'),
    status: 'inProgress',
    dueAt: new Date('2026-02-25T16:00:00'),
    activeUsers: ['u201', 'u5', 'u1'],
    todoAttached: [
      {
        todo: 'Create illustration set',
        addedBy: 'u201',
        isDone: false,
        priority: 'low',
        dueDate: new Date('2026-02-20'),
        reporter: 'u5',
      },
      {
        todo: 'Update brand colors',
        addedBy: 'u5',
        isDone: false,
        priority: 'low',
        dueDate: new Date('2026-02-22'),
        reporter: 'u201',
      },
    ],
    data: {
      title: 'Update Branding Assets',
      content: 'Old logo still appears in footer.',
      description: 'Brand guidelines updated but footer and email templates still use old assets.',
      labels: ['design', 'enhancement'],
      docs: [],
      messages: [],
    },
  },
];

export const dummyUsers: User[] = [
  {
    id: 'u1',
    name: 'Mohd Bilal',
    email: 'bilal@example.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 'u2',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 'u3',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 'u5',
    name: 'Priya Verma',
    email: 'priya.verma@example.com',
    role: 'designer',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 'u10',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@example.com',
    role: 'qa',
    avatar: 'https://i.pravatar.cc/150?img=22',
  },
  {
    id: 'u51',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@example.com',
    role: 'designer',
    avatar: 'https://i.pravatar.cc/150?img=6',
  },
  {
    id: 'u54',
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: 'u100',
    name: 'Neha Kapoor',
    email: 'neha.kapoor@example.com',
    role: 'qa',
    avatar: 'https://i.pravatar.cc/150?img=23',
  },
  {
    id: 'u1030',
    name: 'Imran Khan',
    email: 'imran.khan@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=9',
  },
  {
    id: 'u200',
    name: 'Karan Mehta',
    email: 'karan.mehta@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 'u201',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    role: 'designer',
    avatar: 'https://i.pravatar.cc/150?img=11',
  },
  {
    id: 'u202',
    name: 'Aditya Nair',
    email: 'aditya.nair@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 'u203',
    name: 'Meera Joshi',
    email: 'meera.joshi@example.com',
    role: 'qa',
    avatar: 'https://i.pravatar.cc/150?img=13',
  },
  {
    id: 'u204',
    name: 'Rahul Chatterjee',
    email: 'rahul.chatterjee@example.com',
    role: 'developer',
    avatar: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: 'u205',
    name: 'Divya Pillai',
    email: 'divya.pillai@example.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?img=15',
  },
];
